title: ReadyM docs
description: Documentation for the ReadyM platform.
theme: just-the-docs

url: https://readycodeio.github.io/readym-docs

nav_external_links:
- title: ReadyM home page
  url: https://www.ready.mp
  hide_icon: false
  opens_in_new_tab: true

aux_links: # remove if you don't want this link to appear on your pages
  ReadyM home page: https://www.ready.mp